import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} size-full min-h-screen min-w-[100vw] bg-gradient-to-b from-gray-950 to-gray-900 px-4 sm:px-0`}
      >
        <main className="mx-auto flex min-h-screen max-w-md flex-col items-center justify-center gap-8 py-10">
          {children}
        </main>
      </body>
    </html>
  );
}
